version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: hifumiio-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run build
      - save_cache:
          paths:
            - ~/.m2
          key: hifumiio-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths: .
  lint:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm install
      - run: npm run lint

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - lint
